### ISSUE TITLE
Error - Individuals with Patriarchs

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#101]
webtrees 2.1.16, vesta 2.1.16.1.6
error after clicking on a letter in list of individuals:

Fisharebest\Webtrees\View::{closure}(): Return value must be of type int, Cissee\Webtrees\Module\ExtendedRelationships\SurnameWithPatriarch returned …/resources/views/lists/surnames-column-list.phtml:18
#0 [internal function]: Fisharebest\Webtrees\View::{closure}()
#1 …/resources/views/lists/surnames-column-list.phtml(18): array_map()
#2 …/app/View.php(183): include('...')
#3 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#4 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#5 …/app/Module/IndividualListModule.php(389): view()
#6 …/modules_v4/vesta_extended_relationships/ExtendedIndividualListRequestHandler.php(67): Fisharebest\Webtrees\Module\IndividualListModule->createResponse()
#7 …/app/Http/Middleware/RequestHandler.php(55): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedIndividualListRequestHandler->handle()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()

**Comment by ric2016** [comment]
This is caused by using a non-default setting in the tree preferences ("Surname list style").
Workaround: Set this to 'table', or use the changes from the following commit.
Vesta release with the fix to follow.
