### ISSUE TITLE
MagicSunday\Webtrees\DescendantsChart\Traits\ModuleChartTrait

### ISSUE THREAD

**Issue by HelmutL** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#105]
webtrees 2.1.17, Vesta 2.1.17.0.0
I get a persistent error:
Trait "MagicSunday\Webtrees\DescendantsChart\Traits\ModuleChartTrait" not found

/data/web/e74015/html/webtrees/modules_v4/vesta_extended_relationships/LCAChartModule.php: 30

**Comment by Jefferson49** [comment]
Observed the same behavior in the same configuration (webtrees 2.1.17, vesta 2.1.17.0.0)

**Comment by ric2016** [comment]
Opps, my IDE imported the wrong file -  Fixed in commit, next Vesta release to follow.
