### ISSUE TITLE
Class "Cissee\WebtreesExt\Services\TreeNodeCor" not found

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#106]
Observed with webtrees 2.1.17 and vesta 2.1.17.0.1

If trying to show the common ancestors of certain persons (who seemingly really have common ancestors), a PHP error occurs, see screenshot and stack trace

![Common ancestors](https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/assets/81484983/99c9ad88-80a3-45d5-874f-c454e3c0e5d9)
[Stack trace common ancestors.txt](https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/files/12061181/Stack.trace.common.ancestors.txt)

**Comment by ric2016** [comment]
Do you have the respective file i.e. "modules_v4\vesta_extended_relationships\patchedWebtrees\Services\TreeNodeCOR.php"?

**Comment by Jefferson49** [comment]
The file seems to be there and the class seems to be in the file

![TreeNodeCOR](https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/assets/81484983/23d85ea6-7d82-4feb-905f-b5170ec9379d)
![class TreeNodeCOR](https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/assets/81484983/e95d11ad-170e-43e0-83af-fe0a9deec5b3)

**Comment by ric2016** [comment]
Can you check if the commited change in autoload.php changes anything?

**Comment by Jefferson49** [comment]
No, the provided change in autoload.php does not change anything; same error.

In the mean time, I tried a second webtrees server with a different architecture. On this server, the common ancestors view is working without an error. Is it possible that it depends on the server or the PHP version?

Server 1) => **with** errors
Linux NAS-Synology
PHP 8.0.28

Server 2) => **without** errors
Windows xampp
PHP 8.1.6

Another thing might be worth to mention: When installing webtrees 2.1.17 on server 1), I accidentally installed vesta.2.1.17.0.1 before webtrees 2.1.17. After starting webtrees, a lot of vesta messages were shown and the vesta modules were deactivated. After installing webtrees 2.1.17, everything seemed to be o.k.. Only the discussed error occured.

In order to come to a clean point, I have also deleted all vesta files in the modules_v4 folder and  afterwards inserted the vesta.2.1.17.0.1 files again. However, the error still occurs.

**Comment by ric2016** [comment]
> No, the provided change in autoload.php does not change anything;

After checking more closely that would have been unexpected anyway (I just don't understand how it worked at all without that line, but that seems to be a different topic).

The method where the error occurs is in the same namespace as the missing class (and the files are in the same directory), so my only explanation is that the file is somehow corrupt, or has the wrong access rights, in that installation, although you said you replaced all files already ...

**Comment by ric2016** [comment]
> Server 1) => with errors
> Linux NAS-Synology
> 
> Server 2) => without errors
> Windows xampp

Now I see it - It's a case issue that doesn't show under windows (which I use for developing):

"TreeNodeCor" vs "TreeNodeCOR"

**Comment by Jefferson49** [comment]
Thank you for the bugifx. A test on my Linux server was successful!
