### ISSUE TITLE
Menu item name "Compact pedigree" is not translated

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#108]
Observed with webtrees 2.1.17 and vesta 2.1.17.0.1

![Compact pedigree](https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/assets/81484983/2016c201-0bfa-4866-80a0-8ca1ee1111a1)

It seems that vesta refers to a translation in webtrees. However, the translation does not exist in webtrees:

```
public function title(): string {
	if (self::KIND_COMPACT == $this->kind) {
		return $this->getVestaSymbol() . ' ' . MoreI18N::xlate('Compact pedigree');
	}
```

The corresponding chart in webtrees is called "**Compact tree**". Probably, the code above needs to be changed to this name.

**Comment by ric2016** [comment]
Thanks - Changed in code (one other string was missing as well) and available to translate on Weblate.
