### ISSUE TITLE
Compact pedigree is less compact than (normal) pedigree

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#110]
Observed with webtrees 2.1.17 and vesta 2.1.17.0.1

It seems that the "Compact pedigree" is less compact than the "Pedigree", see screenshot. Is it possible that the menu items are pointing to the wrong chart? Or some other mixup of the two charts?

**Pedigree:**

![Pedigree](https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/assets/81484983/3558550a-8660-4b58-8ecf-225e2524f447)

**Compact pedigree:**

![Pedigree compact](https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/assets/81484983/e0afe20e-750e-49b3-9d21-ebf894f8b9e7)

**Comment by ric2016** [comment]
The 'compact pedigree' chart displays repeated ancestors only once (in your example, there aren't any). It uses markers for these repeated ancestors (as in the pedigree collapse chart), for which extra space is reserved.

I'll check if this extra space can be removed via css if it isn't actually required. A different name for the chart also may be helpful.

**Comment by Jefferson49** [comment]
Thank you for the explanation. Now, I fully understand the background. I tried it with some of my individuals and it works very well.

I agree that a different name for the "Pedigree compact" is needed. However, it is difficult to come up with a good proposal for a short name. Some ideas:
- Pedigree with pedigree collapse / Vorfahrentafel mit Ahnenschwund
- Pedigree incl. pedigree collapse / Vorfahrentafel incl. Ahnenschwund
- Pedigree with integrated pedigree collapse / Vorfahrentafel mit integriertem Ahnenschwund
- Pedigree (incl. collapse) / Vorfahrentafel (incl. Ahnenschwund)

**Comment by ric2016** [comment]
I'll probably merge the two charts and offer the functionality of 'compact pedigree' as an additional option, that way it's easier to explain.

**Comment by ric2016** [comment]
Merge implemented in 2.1.17.0.3.
