### ISSUE TITLE
Default values for generations in pedigree charts

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#111]
Observed with webtrees 2.1.17 and vesta 2.1.17.0.1

Currently, the default values for generations are set to "unlimited". However, the calculation for the pedigrees is sometimes time consuming.

Therefore, I would like to propose the following default values:
- Pedigree: 5
- Pedigree compact: 5
- Pedigree collapse: unlimited (due to the specific intention of this chart)

**Comment by ric2016** [comment]
5 seems a bit low, I've set the default for the merged Pedigree chart to 8 now, which should process quickly enough.
