### ISSUE TITLE
Privacy setting & List Individuals with Patriarchs

### ISSUE THREAD

**Issue by SnarfW** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#120]
I noticed that privacy settings are handled differently on the Individuals with Patriarchs list versus the standard Individuals list. I noticed this behaviour on my own site and could reproduce on your site:

On the Individuals with Patriarchs list I can for instance see the details of persons born after 1913 

[https://cissee.de/webtrees2/tree/tree/individual-patriarchs-list?surname=Drewes%20%5BMe%C3%9Fhausen%5D](url)

While they are not shown on the standard list:

[https://cissee.de/webtrees2/tree/tree/individual-list?show_all_firstnames=yes&surname=DREWES%20%5BMESSHAUSEN%5D&falpha=&show_marnm=#](url)

**Comment by ric2016** [comment]
Thank you for the report, that's a critical bug and certainly unintended.
I advise to disable the list (as I just did on my page) until this is fixed.

**Comment by ric2016** [comment]
Fixed in latest commit, release to follow.

This was caused by the fix for #101, which just reset all tree preferences, including privacy-relevant ones. Not sure what I was thinking there ...

**Comment by ric2016** [comment]
Release is out now.

**Comment by SnarfW** [comment]
Thanks for the prompt fix!
