### ISSUE TITLE
php 8.3 , surnames with patriarchs

### ISSUE THREAD

**Issue by arbor95** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#124]
nach Umstellung auf php 8.3 kommt:
after switching to php 8.3 comes:

array_sum(): Addition is not supported on type Cissee\Webtrees\Module\ExtendedRelationships\SurnameWithPatriarch …/modules_v4/vesta_extended_relationships/resources/views/lists/surnames-table-with-patriarchs.phtml:119

zurück auf 8.2 ist wieder OK.
back to 8.2 is OK again.

See: https://wiki.php.net/rfc/saner-array-sum-product

**Comment by ric2016** [comment]
Even with php 8.2, the code doesn't make any sense: There is no effect when trying to order by that column.
I have disabled the ordering altogether.

**Comment by ric2016** [comment]
Also occurs here:

array_sum(): Addition is not supported on type Cissee\Webtrees\Module\ExtendedRelationships\SurnameWithPatriarch …/modules_v4/vesta_extended_relationships/IndividualListModule_2_1_16.php:413

**Comment by ric2016** [comment]
Also fixed in commit for #126.
