### ISSUE TITLE
modules do not show up

### ISSUE THREAD

**Issue by bmhm** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#13]
Hi,

I am trying to install the modules as provided per installation section.

No vesta modules show up.
No errors in php error log, no entries in webtree’s inbuilt log.

Btw: there is no such menu "Control Panel -> Modules -> Module Administration". There is just "all modules" where no vesta* modules appear. :-(

Any idea where to start looking?

**Comment by ric2016** [comment]
> no such menu "Control Panel -> Modules -> Module Administration"

Thanks for the note - I'll adjust the Readme files.

Regarding your problem, there are a few things to check:
1. Do other custom modules work?
2. Are the Vesta modules installed in the correct location? The folder structure should look like this (top-level folder may be named differently, usually 'webtrees'):

![modules](https://user-images.githubusercontent.com/18174787/97342904-21b39180-1887-11eb-9258-92fd890db1bc.png)

**Comment by bmhm** [comment]
Hi,

I am using webtrees 2.0.10 (latest).

1. 
I do not use other custom modules so far.

2. 
I do not use graphical browsers, but yes…

```
[bmhm@arche modules_v4] wget https://cissee.de/vesta.latest.zip
[bmhm@arche modules_v4] cd ..
[bmhm@arche webtrees] unzip -x modules_v4/vesta.latest.zip
[bmhm@arche webtrees]$ ll modules_v4/
total 4,0M
-rw-r--r--. 1 bmhm bmhm 6,8K 17. Mär 2020  README.md
drwxrwxr-x. 6 bmhm bmhm 4,0K 25. Okt 09:20 vesta_classic_look_and_feel/
drwxrwxr-x. 4 bmhm bmhm  227 25. Okt 09:20 vesta_clippings_cart/
drwxrwxr-x. 9 bmhm bmhm 4,0K 25. Okt 09:20 vesta_common/
drwxrwxr-x. 4 bmhm bmhm 4,0K 25. Okt 09:20 vesta_extended_relationships/
drwxrwxr-x. 6 bmhm bmhm 4,0K 25. Okt 09:20 vesta_gov4webtrees/
-rw-rw-r--. 1 bmhm bmhm 4,0M 25. Okt 09:31 vesta.latest.zip
drwxrwxr-x. 3 bmhm bmhm  174 25. Okt 09:20 vesta_location_data/
drwxrwxr-x. 6 bmhm bmhm 4,0K 25. Okt 09:20 vesta_personal_facts/
drwxrwxr-x. 4 bmhm bmhm 4,0K 25. Okt 09:20 vesta_places_and_pedigree_map/
drwxrwxr-x. 5 bmhm bmhm 4,0K 25. Okt 09:20 vesta_relatives/
drwxrwxr-x. 6 bmhm bmhm 4,0K 25. Okt 09:20 vesta_research_suggestions/
drwxrwxr-x. 6 bmhm bmhm 4,0K 25. Okt 09:20 vesta_shared_places/

[bmhm@arche webtrees]$ ll modules_v4/vesta_common/
total 96K
-rw-rw-r--. 1 bmhm bmhm 1006  4. Jul 19:33 autoload.php
-rw-rw-r--. 1 bmhm bmhm 6,7K 19. Sep 13:42 CommonI18N.php
drwxrwxr-x. 3 bmhm bmhm   48 11. Okt 09:39 controlpanel/
drwxrwxr-x. 3 bmhm bmhm  228 11. Okt 09:39 docs/
drwxrwxr-x. 2 bmhm bmhm 4,0K 11. Okt 09:39 HookInterfaces/
-rw-rw-r--. 1 bmhm bmhm   10 17. Okt 09:38 latest-version.txt
-rw-rw-r--. 1 bmhm bmhm  36K  5. Jan 2020  LICENSE.md
drwxrwxr-x. 2 bmhm bmhm  204 11. Okt 09:39 model/
-rw-rw-r--. 1 bmhm bmhm  826  7. Jun 18:45 ModuleI18N.php
-rw-rw-r--. 1 bmhm bmhm  372  1. Jun 2019  module.php
drwxrwxr-x. 6 bmhm bmhm  175 11. Okt 09:39 patchedWebtrees/
-rw-rw-r--. 1 bmhm bmhm  567  5. Jun 19:44 po.bat
-rw-rw-r--. 1 bmhm bmhm 2,5K 17. Okt 09:40 README.md
drwxrwxr-x. 4 bmhm bmhm   31 11. Okt 09:39 resources/
-rw-rw-r--. 1 bmhm bmhm 1,5K 10. Nov 2019  VestaAdminController.php
-rw-rw-r--. 1 bmhm bmhm 1,9K 19. Sep 12:02 VestaCommonLibModule.php
-rw-rw-r--. 1 bmhm bmhm 3,0K 24. Aug 20:58 VestaModuleCustomTrait.php
-rw-rw-r--. 1 bmhm bmhm  11K 19. Sep 12:04 VestaModuleTrait.php
drwxrwxr-x. 2 bmhm bmhm   48 11. Okt 09:39 WhatsNew/

```

**Comment by ric2016** [comment]
Well, that looks ok - assuming that it is the correct 'modules_v4' folder, which the README.md seems to indicate. So you removed the other example custom modules? I'd suggest to restore one of them and enable it (by renaming the folder), and then check whether that module appears in the list of custom modules.

**Comment by bmhm** [comment]
"Kaum macht man’s richtig, funktionierts".

I browsed the wrong webtrees folder. Sorry for the fuzz… nvm…
