### ISSUE TITLE
Error message with release 2.0.10.5.0

### ISSUE THREAD

**Issue by mpwt** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#21]
When I upload the module, I get the error message on an otherwise empty page after calling up or reloading the page:

```
Trait 'Cissee\Webtrees\Hook\HookInterfaces\EmptyRelativesTabExtender' not found

/home/bauschaf/webtrees_ffp2/modules_v4/vesta_extended_relationships/ExtendedRelationshipModule.php: 70
```

The following parts of your vesta package are installed or uploaded:
vesta_classic_look_and_feel
vesta_common
vesta_extended_relationships (only uploaded)
vesta_location_data
vesta_personal_facts

**Comment by ric2016** [comment]
See [here](https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships#download) for the required modules. You're missing 'vesta_families'. The easiest option is to always upload all vesta folders.

**Comment by mpwt** [comment]
But 'vesta_families' isn't included in the latest release. Do you mean 'vesta_relatives'. 

'vesta_common' is installed.

**Comment by ric2016** [comment]
Yes, 'vesta_relatives', that's an error in the Readme.
Again, you have to install all required modules listed there, including "the ⚶ Vesta Families module".

**Comment by mpwt** [comment]
Now it works. Thank you very much.
