### ISSUE TITLE
List Individuals with Patriarchs ?

### ISSUE THREAD

**Issue by mpwt** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#23]
Hallo, mit der aktuellen Version wird unter Listen ein zusätzlicher Punkt "Individuals with Patriarchs" angezeigt. Deaktiviere ich dies unter Verwaltung / Listen wird auch Beziehungen unter Diagrammen deaktiviert.

Was bedeute dieser neue Punkt?

![C621AEFC-808F-41CD-AD55-E6A84B7D294C](https://user-images.githubusercontent.com/16311627/106383217-f92abe80-63c4-11eb-90be-a1ae1a7bdecc.jpeg)

**Comment by ric2016** [comment]
> Deaktiviere ich dies unter Verwaltung / Listen wird auch Beziehungen unter Diagrammen deaktiviert.

Ja, die Checkbox deaktiviert das gesamte Modul, das ist etwas unschön. Lösung: Bei Bedarf diese Liste dort über "Zugriffsrechte > für niemand zeigen" verstecken.

> Was bedeute dieser neue Punkt?

Ich hatte gedacht, das wäre selbsterklärend sein beim Listenaufruf: Es wird jeweils der Spitzenahn in männlicher Linie angezeigt, so daß erkennbar ist, ob alle Träger eines bestimmten Namens tatsächlich zusammenhängen. So wird es ja auch im "What's New ..." beschrieben.

**Comment by mpwt** [comment]
Vielen Dank für die Erklärung. Die Datei What's new" habe ich im Dateiverzeichnis gefunden ... oder ist die auch an andere Stelle sichtbar / aufrufbar?

Anmerkung: Ich glaube, dass "Patriarch" als Bezeichnung nicht ganz korrekt ist (zumindest, wenn ich mir die Begriffserklärung in Wikipedia anschaue). Eher ist es der Spitzahn / Tree top.

**Comment by ric2016** [comment]
"What's new" wird einmalig nach der Installation der aktualisierten Module angezeigt in Webtrees - jedenfalls sollte es so sein.

Zur Terminologie: Ja, es gibt wohl keinen ganz passenden Begriff. Ich habe mich hieran orientiert: https://genealogy.stackexchange.com/questions/8021/what-is-the-english-equivalent-to-the-german-term-spitzenahn
