### ISSUE TITLE
Feature request: using SVG when generating relationship diagram

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#33]
magicsunday uses SVG to generate [pedigree](https://github.com/magicsunday/webtrees-pedigree-chart) and [descendant](https://github.com/magicsunday/webtrees-descendants-chart) charts. Using his approach would be a great enhancement for relationship diagrams, too. Very often these relationship diagrams are so large that they do not fit even on a PC screen. What do you think about replacing the existing old-fashioned and not scalable graphics by SVG?

**Comment by ric2016** [comment]
I agree the current charts should be modernized eventually. I'll leave this task to someone else though ;-) I'm not a UI developer myself. If there was a modernized relationship chart, I could use its code optionally.

In general I'm not sure the SVG approach is the most useful one, as there are no hyperlinks or any of the other per-individual options of the old diagrams.
