### ISSUE TITLE
Relationships in Charts menu

### ISSUE THREAD

**Issue by HRN65** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#4]
Relationships doesn't order alphabetically, but shows on top in the Charts menu.

![relationships](https://user-images.githubusercontent.com/55854079/82948878-eee93280-9fa2-11ea-9777-bd895566a668.jpg)

**Comment by ric2016** [comment]
This is a webtrees issue, to be fixed there (see [PR](https://github.com/fisharebest/webtrees/pull/3306)).
