### ISSUE TITLE
Wrong relationship on own page

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#46]
When I'm on my own page the relationship is corrupted. Maybe it should be omitted in this case.

![Screenshot (263)_LI](https://user-images.githubusercontent.com/6324175/116088120-db0deb00-a6a1-11eb-9ae9-5bc505312b57.jpg)

**Comment by ric2016** [comment]
(fixed in code but not released yet)
