### ISSUE TITLE
Inconsistent count of relationships when searching for relationsship between identical persons

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#47]
Maybe it makes no sense to search for relationships between identical persons, but even then it should be consistent: **one** relationship or **no** relationship.

![Screenshot (264)_LI](https://user-images.githubusercontent.com/6324175/116091804-7d7b9d80-a6a5-11eb-8162-6a7c6b68b71f.jpg)

**Comment by ric2016** [comment]
(fixed in code but not released yet)
