### ISSUE TITLE
Relationship problem with marriage witnesses

### ISSUE THREAD

**Issue by JLL76** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#51]
I am using WT 2.0.16 and vesta 2.0.16.1.0
Attached 2 screenshots for a problem noted:
using Vesta's Facts & Events, there is no relationship displayed for the 2nd and 3rd witness! on the other hand for classic Facts & Events, it works!
![Vesta Fact Event](https://user-images.githubusercontent.com/65648013/119251323-55993000-bba6-11eb-8d20-6769296597b9.JPG)
![Fact Event](https://user-images.githubusercontent.com/65648013/119251339-5e8a0180-bba6-11eb-8f3a-6bde3078f6d1.JPG)

**Comment by ric2016** [comment]
I'm afraid I cannot reproduce this.

These relationships are loaded via separate ajax requests. If some of these requests fail for some reason, that would explain the output as shown in your screenshot.

Can you check whether there are any such failing requests, specifically requests returning with a non-200 code ([see here for details](https://webtrees.net/faq/xhr/))? Is your tree online?

**Comment by JLL76** [comment]
http://arbrelelievre.yj.fr/webtrees/index.php?route=%2Fwebtrees%2Ftree%2FLELIEVRE%2Findividual%2FX1503%2FMarie-MARGUERITE-LELIEVRE#tab-_vesta_personal_facts_
Marie MARGUERITE LELIEVRE 1738–1815 – webtrees <http://arbrelelievre.yj.fr/webtrees/index.php?route=%2Fwebtrees%2Ftree%2FLELIEVRE%2Findividual%2FX1503%2FMarie-MARGUERITE-LELIEVRE#tab-_vesta_personal_facts_>
Naissance 12 décembre 1738 Foucart, Décès 2 janvier 1815 Yvetot, Parents JACQUES Philippe? LELIEVRE + MARIE RIARD (F51), Conjoint ROBERT BEAUSSAY, Conjoint PIERRE Guillaume Francois DESMEULLES, Enfants AIMABLE
arbrelelievre.yj.fr



________________________________
De : Richard Cissée ***@***.***>
Envoyé : dimanche 23 mai 2021 09:32
À : vesta-webtrees-2-custom-modules/vesta_extended_relationships ***@***.***>
Cc : JLL76 ***@***.***>; Author ***@***.***>
Objet : Re: [vesta-webtrees-2-custom-modules/vesta_extended_relationships] Relationship problem with marriage witnesses (#51)


I'm afraid I cannot reproduce this.

These relationships are loaded via separate ajax requests. If some of these requests fail for some reason, that would explain the output as shown in your screenshot.

Can you check whether there are any such failing requests, specifically requests returning with a non-200 code (see here for details<https://webtrees.net/faq/xhr/>)? Is your tree online?

**Comment by ric2016** [comment]
When I view this page, there are now no relationships displayed at all, not even for the first witness.

There seems to be a general problem with several requests (not restricted to Vesta modules), see the screenshot. You should probably fix these first - you may have to adjust your web server configuration.

![508](https://user-images.githubusercontent.com/18174787/119252535-2a660f00-bbad-11eb-877d-445fc7762f29.PNG)
![response](https://user-images.githubusercontent.com/18174787/119252538-2d60ff80-bbad-11eb-8a87-b6908718cfba.PNG)

**Comment by JLL76** [comment]
Thank you for the answer!
Indeed I noticed that my free host offer is too limited for webtrees. On the other hand I do not understand why the display is done perfectly and instantly on the Fact & Events tab (non vesta)?
Jean-Luc
________________________________
De : Richard Cissée ***@***.***>
Envoyé : dimanche 23 mai 2021 09:57
À : vesta-webtrees-2-custom-modules/vesta_extended_relationships ***@***.***>
Cc : JLL76 ***@***.***>; Author ***@***.***>
Objet : Re: [vesta-webtrees-2-custom-modules/vesta_extended_relationships] Relationship problem with marriage witnesses (#51)


When I view this page, there are now no relationships displayed at all, not even for the first witness.

There seems to be a general problem with several requests (not restricted to Vesta modules), see the screenshot. You should probably fix these first - you may have to adjust your web server configuration.

[508]<https://user-images.githubusercontent.com/18174787/119252535-2a660f00-bbad-11eb-877d-445fc7762f29.PNG>
[response]<https://user-images.githubusercontent.com/18174787/119252538-2d60ff80-bbad-11eb-8a87-b6908718cfba.PNG>

**Comment by ric2016** [comment]
> On the other hand I do not understand why the display is done perfectly and instantly on the Fact & Events tab (non vesta)?

Because on the original tab the relationships are not loaded via separate requests - However, this has the effect that the entire page takes more time to load.

I decided to use separate requests because the extended tabs show additional relationships (such as the relationship to the default individual), the calculation of which takes additional time.
