### ISSUE TITLE
webtrees 2.0.1.9 and PHP 8.0 extended relationship error

### ISSUE THREAD

**Issue by Shemwell** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#61]
Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /home/rbiowmpf/public_html/webtrees2/modules_v4/vesta_extended_relationships/patchedWebtrees/Relationships/RelDef.php on line 58

**Comment by ric2016** [comment]
[webtrees 2.0 does not support php 8](https://webtrees.net/download), and therefore the respective Vesta releases in general don't, either. This particular issue will be easy to fix, but there may be others.

**Comment by ric2016** [comment]
Should be fixed in Release 2.0.19.1.0.
