### ISSUE TITLE
Error on tab Facts and events

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#69]
vesta modules 2.0.23.0.0, webtrees 2.0.23:
with Relationships checked

![Výběr_255](https://user-images.githubusercontent.com/350656/161594055-96b5ef73-8ade-4b3f-926f-64a006347016.jpg)

**Comment by ric2016** [comment]
Fixed in latest release 2.0.23+2.1.0-beta.2.0.1
