### ISSUE TITLE
Wrong identification of relationship

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#7]
In the following case, in my opinion, it should be called "Schwiegersohns Neffe" or "Tochters Schwiegerneffe" (not so good).

![Screenshot (113)](https://user-images.githubusercontent.com/6324175/85840918-a12c3980-b79d-11ea-876b-2785b896f421.png)

**Comment by ric2016** [comment]
In-law relationships are not modelled separately in webtrees in general (in any language), e.g. there is no distinction between 'uncle' (brother of a parent) and 'uncle' (husband of a parent's sister).

In addition to that, language-specific relationships are an open issue for several years now (this is rather frustrating, see e.g. [this issue](https://github.com/fisharebest/webtrees/issues/2331), [original issues go back much further](https://github.com/fisharebest/webtrees/pull/928)).

I'll probably have to discuss the planned roadmap for these issues in webtrees first, and then decide whether to implement something specific in this module.

**Comment by ric2016** [comment]
Finally, I hope to handle this via #36.

**Comment by hartenthaler** [comment]
With the new module function this is solved now. Great!!! Thanks a lot!
