### ISSUE TITLE
Very slow rendering (+4 seconds)

### ISSUE THREAD

**Issue by ronaaron** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#82]
Hello -
I just upgraded to the latest Webtrees release, and updated Vesta as well. I'm actually now using your git version, not the released one, in hopes it would fix this issue (it didn't).

The extended relationships does two fetches which are taking a long time, it would be great if they could be done at least in parallel:

![image](https://user-images.githubusercontent.com/17123974/180966653-4bb1d51b-84ce-4411-8bc4-e09453477bff.png)

**Comment by ric2016** [comment]
The second request is done via Ajax because it may take longer. At this point, the page should be rendered though. The first request determines, among other things, the inputs for the second one, so it's not really possible to run them in parallel.

In any case, the first request shouldn't be substantially slower than a similar request for the original webtrees tab. It may be slow e.g. due to a large number of facts, such as historic events.

**Comment by ronaaron** [comment]
Hmm. I wonder if there isn't some way to make the first request get more information?
In any event, I can try to make the database run faster on the admittedly slow machine it's on.

**Comment by ric2016** [comment]
That would slow down the initial rendering of the page.

Can you confirm that the time is about the same when using the regular tab, or is it substantially slower?

**Comment by ronaaron** [comment]
From what I can see, any page takes about as long.

**Comment by ronaaron** [comment]
A point of information:

A particular page with basically no links takes almost 6 seconds to load. After I remove all the vesta stuff (e.g. clean out modules_v4), the same page takes 450ms to load.

That implies it's not the database load per se, but something to do with the vesta modules.

**Comment by ric2016** [comment]
I may have to analyze this further - I'm currently on holiday though, so this will have to wait (about two weeks).

**Comment by ronaaron** [comment]
Thank you, I'm most interested. Have a good vacation.

**Comment by ric2016** [comment]
Is this still an issue? Is there a way for me to reproduce this on your server?

**Comment by ronaaron** [comment]
It should still be an issue, but I disabled the vesta stuff because it was really slowing the system down.

**Comment by ric2016** [comment]
I'm afraid I cannot reproduce this on my servers.

**Comment by ric2016** [comment]
(reopen if there is a way to reproduce this)
