### ISSUE TITLE
Relationships - 'Individual 2' not automatically set to default individual

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#86]
In webtrees 2.0.x `Individual 2` was automatically set to the `default individual`.

In webtrees 2.1.12 with Vesta Webtrees Custom Modules 2.1.10.0.0 this `Individual 2` is empty by default.

Is it possible to set it again automatically to the `default individual`?

**Comment by ric2016** [comment]
This seems to be a webtrees issue (see the regular 'Relationships' chart) - I don't think Vesta ever did this differently from webtrees?

**Comment by TheDutchJewel** [comment]
Oops, I had to link myself again in `Control panel / User administration / Edit the user / Access to family trees / Individual record`.
