### ISSUE TITLE
500 Error (2.1.13)

### ISSUE THREAD

**Issue by HRN65** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#87]
Using latest version 2.1.13 I get a 500 error

In my server error log I find:

[Thu Dec 15 21:55:25.278518 2022] [proxy_fcgi:error] [pid 47342:tid 139903283209984] [client 136.243.228.197:0] AH01071: Got error 'PHP message: PHP Fatal error:  Declaration of Cissee\\Webtrees\\Module\\ExtendedRelationships\\ExtendedIndividualListController::individuals(Fisharebest\\Webtrees\\Tree $tree, string $surname, array $surnames, string $galpha, bool $marnm, bool $fams): Illuminate\\Support\\Collection must be compatible with Fisharebest\\Webtrees\\Module\\IndividualListModule::individuals(Fisharebest\\Webtrees\\Tree $tree, string $surn, string $salpha, string $galpha, bool $marnm, bool $fams, Fisharebest\\Localization\\Locale\\LocaleInterface $locale): Illuminate\\Support\\Collection in /var/www/vhosts/visitusinmaputo.com/httpdocs/webtree/modules_v4/vesta_extended_relationships/ExtendedIndividualListController.php on line 184'

**Comment by ric2016** [comment]
The Vesta code had to be adjusted to align with the latest webtrees release - apparently you are not using webtrees 2.1.13?
See the function signature [here](https://github.com/fisharebest/webtrees/blob/61cc2bb7af712f92e4566116b7029073286e5201/app/Module/IndividualListModule.php#L703).

The error message says it expects a different signature from a previous webtrees version, so your webtrees IndividualListModule.php doesn't seem to be up-to-date.

**Comment by Jefferson49** [comment]
With webtrees 2.1.13 and Vesta 2.1.13.0.0, I get the same PHP error, and webtrees does not statt.

Fatal error: Declaration of Cissee\Webtrees\Module\ExtendedRelationships\ExtendedIndividualListController::individuals(Fisharebest\Webtrees\Tree $tree, string $surname, array $surnames, string $galpha, bool $marnm, bool $fams): Illuminate\Support\Collection must be compatible with Fisharebest\Webtrees\Module\IndividualListModule::individuals(Fisharebest\Webtrees\Tree $tree, string $surn, string $salpha, string $galpha, bool $marnm, bool $fams, Fisharebest\Localization\Locale\LocaleInterface $locale): Illuminate\Support\Collection in /volume1/web/webtrees/modules_v4/vesta_extended_relationships/ExtendedIndividualListController.php on line 184

**Comment by ric2016** [comment]
Yes, see adjusted comment above, I'll have to fix this.

**Comment by ric2016** [comment]
Fixed in Release 2.1.13.0.1.
It should also work to just replace the file ExtendedIndividualListController.php [with the current version](https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/blob/1f1305a878189bdfccf1bc3e731378a1a1672151/ExtendedIndividualListController.php) (which is actually the same as earlier versions before 2.1.13)

**Comment by HRN65** [comment]
Thank you!
