### ISSUE TITLE
Patriarchs list

### ISSUE THREAD

**Issue by ghezibde** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#91]
The list Individuals with Patriarchs will fail most of the time on my website.
I guess this is linked with the fact the gedcom i'm working on is really big.
Is there a way to disable this list (or to limit the results of that request), could not find an option to do that ?

`SQLSTATE[HY000]: General error: 1390 Prepared statement contains too many placeholders (SQL: select `i_id` as `xref`, `i_gedcom` as `gedcom` from `wt_individuals` where `i_file` = 9 and `i_id` in (X3854, X10071, X67969, X81195, X81811, X108484, X147305, X147687, X13922, X32997, I77972, I15124, X124218, X126489, X45942, X90688, X90699, X136221, X6234, X44181, X48837, X86716, I260442, I301389, I415564, I419055, X101639, X104828, I2966, I1400, X142976, X127567, X84762, I301919, X8142, I216819, I28090, I145905, I41976, I44025, I52634, X33934, I88605, X21640, X47410, X53021, X76496, X84937, X95161, I132103, I157443, I157797, I438663, I278451, I255280, I258648, I421771, I440675, I444034, I451616, X131254, X151149, X154631, X28364, I430504, X126862, X151395, I242555, I266938, I164933, I292540, X4118, X5305, X8235, I16280, I32421, I100262, I454206, X20983, X71639, I141316, I144586, I149778, I163669, I164341, I169012, I173410, I189648, I238574, I253597, I257179, I264469, I267971, I416172, I429870, I440471, I454848, X124620, I285487, X29239, X102947, I426633, I177772, I198420, I198428, X7525, X148178, I145981, I256854, I272465, I247266, I1546, X33676, X11727, I158534, X11746, X55386, I140218, I286138, I303225, I448168, I454242, X118279, I186467, X84876, I136148, I96397, I245215, I4920, 
(...)
I163978, I284788, I285294, I286068, I419375, I429643, I429721, I442700, X113480, X129034, I250602, I251835, I251475, I99849, I295439, I104706, I134079, I172676, I185516, I277139, I309719, I437376, I66960, I16883, I44910, X52749, X97835, I184586, I252232, I451268, X124705, I432990, X44084, X14990, X47981, I126734, I104144, I270287, I166549, I229509, I289195, X132144, I64989, I101677, I146762, X103826, I32969, I57787, I61418, I62340, I97579, I146896, X19110, X24285, I280552, X61280, X78231, X90631, X95044, I138348, I434074,  I83521, X90755, I83520, X72649, X36509, I143891, I456785, I105487, X38103, X75164, I116515, I179110, I83514, I139158, I23091, I186773, X71943, I456530, X52532, X90751, X72581, X73877, I26783, X142938, X64759, X107359, X29148, I15123, X119058, I80638, X72603, I226429, X105143, I50369, X91914, X91916, I253778, X122247, X75995, X77882, X78010, X79363, X86587, X88816, X106243, X136043, X126526, X83999, I250135, I94080, I258551, I65693, X118607, I182827, I154475, I278101, X108488, X14351, I80682, I177521, X72580, I84028, I161753, I83513, I452094, I83598, I83491, I30198, I65553, X101457, X66766, X136030, X134676, I148724, I261933, I59984, I311633)) …/vendor/illuminate/database/Connection.php:712
#0 …/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#1 …/vendor/illuminate/database/Connection.php(376): Illuminate\Database\Connection->run()
#2 …/vendor/illuminate/database/Query/Builder.php(2414): Illuminate\Database\Connection->select()
#3 …/vendor/illuminate/database/Query/Builder.php(2402): Illuminate\Database\Query\Builder->runSelect()
#4 …/vendor/illuminate/database/Query/Builder.php(2936): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 …/vendor/illuminate/database/Query/Builder.php(2403): Illuminate\Database\Query\Builder->onceWithColumns()
#6 …/modules_v4/vesta_extended_relationships/ExtendedIndividualListRequestHandler.php(218): Illuminate\Database\Query\Builder->get()
#7 …/modules_v4/vesta_extended_relationships/ExtendedIndividualListRequestHandler.php(147): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedIndividualListRequestHandler::load()
#8 …/modules_v4/vesta_extended_relationships/ExtendedIndividualListRequestHandler.php(65): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedIndividualListRequestHandler->allSurnamesWithPatriarchs()
#9 …/app/Module/IndividualListModule.php(222): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedIndividualListRequestHandler->allSurnames()
#10 …/app/Module/IndividualListModule.php(172): Fisharebest\Webtrees\Module\IndividualListModule->createResponse()
#11 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Module\IndividualListModule->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#13 …/modules_v4/faces/src/Modules/FacesModule.php(94): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process()
#15 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#17 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher->handle()
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#19 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#22 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#23 …/app/Http/Middleware/Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#25 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#27 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#29 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#31 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#33 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#34 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#35 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#37 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#39 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#41 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#43 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#45 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#47 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#49 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#51 …/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher->handle()
#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#53 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#55 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#57 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#58 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#60 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#62 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#63 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#64 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#65 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#66 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#67 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#68 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#69 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#70 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#71 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#72 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#73 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#74 {main}`

**Comment by ric2016** [comment]
I'll check if this error can be avoided.

Workaround: Disabling this list will disable the entire module, unfortunately; but you can set the access level of this list (it shows up in the control panel under  Control panel > All modules > Lists as "Vesta Extended Relationships") to "Hide from everyone", this will not affect the rest of the module.

**Comment by ric2016** [comment]
Should be fixed by the commit referenced above - Can you test and confirm this?

**Comment by ghezibde** [comment]
I sent you an answer to this question by mail.
SQL error's gone away but bulk result of the select is display on the screen and the list is empty.
url to display an example sent to your email box

**Comment by ric2016** [comment]
Thanks, I'll have to investigate. Looks like a another bug unrelated to this one.

**Comment by ghezibde** [comment]
Patriarchs list worked in 2.1.13.
Both bugs were not present.
Thanks

**Comment by ric2016** [comment]
> Patriarchs list worked in 2.1.13.

the list re-uses code from webtrees, which changed since then.

**Comment by ghezibde** [comment]
Patriarchs list worked in 2.1.13.
Both bugs were not present.
Thanks

>

**Comment by ghezibde** [comment]
Just tried https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/commit/c3da0c3276753cb2c1d362a36c7f28f2dbb77128 .
As you can verify by yourself, everything's ok now (i have to admit i do not use this list a lot, seems i use branchs lists for same purpose; i do not understand why married names are included, how Alive, Dead, Roots, Leaves work. I use those in Ancestors charts with no trouble).
Thanks for solving those two bugs

**Comment by ghezibde** [comment]
AFAICS, the two issues contained in the ticket are solved,
Thanks
