### ISSUE TITLE
Error found in Logfile

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#99]
> Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule …/vendor/aura/router/src/Map.php:189 #0 …/app/Factories/RouteFactory.php(62): Aura\Router\Map-&gt;getRoute() #1 …/app/Helpers/functions.php(132): Fisharebest\Webtrees\Factories\RouteFactory-&gt;route() <b>#2 …/modules_v4/vesta_extended_relationships/ExtendedRelationshipModule.php(660): route()</b> <b>#3 …/modules_v4/vesta_extended_relationships/ExtendedRelationshipModule.php(689): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule-&gt;chartUrl()</b> #4 …/app/Module/ChartsMenuModule.php(99):

**Comment by ric2016** [comment]
I don't see how this can occur (router cannot provider the route previously registered by the customn module).
Is there a way to reproduce it - Or is at least the full stack trace available?

**Comment by hartenthaler** [comment]
The error occurred several times when nobody is logged in (no user, no tree, IP=52.167.144.79).

`Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule …/vendor/aura/router/src/Map.php:189 #0 …/app/Factories/RouteFactory.php(62): Aura\Router\Map-&gt;getRoute() #1 …/app/Helpers/functions.php(132): Fisharebest\Webtrees\Factories\RouteFactory-&gt;route() <b>#2 …/modules_v4/vesta_extended_relationships/ExtendedRelationshipModule.php(660): route()</b> <b>#3 …/modules_v4/vesta_extended_relationships/ExtendedRelationshipModule.php(689): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule-&gt;chartUrl()</b> #4 …/app/Module/ChartsMenuModule.php(99): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule-&gt;chartMenu() #5 [internal function]: Fisharebest\Webtrees\Module\ChartsMenuModule::Fisharebest\Webtrees\Module\{closure}() #6 …/vendor/illuminate/collections/Collection.php(695): array_map() #7 …/app/Module/ChartsMenuModule.php(98): Illuminate\Support\Collection-&gt;map() #8 …/app/Module/ModuleThemeTrait.php(495): Fisharebest\Webtrees\Module\ChartsMenuModule-&gt;getMenu() #9 [internal function]: Fisharebest\Webtrees\Module\WebtreesTheme::Fisharebest\Webtrees\Module\{closure}() #10 …/vendor/illuminate/collections/Collection.php(695): array_map() #11 …/app/Module/ModuleThemeTrait.php(495): Illuminate\Support\Collection-&gt;map() #12 …/resources/views/layouts/default.phtml(112): Fisharebest\Webtrees\Module\WebtreesTheme-&gt;genealogyMenu() #13 …/app/View.php(183): include(&#039;...&#039;) #14 …/app/View.php(278): Fisharebest\Webtrees\View-&gt;render() #15 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make() #16 …/app/Http/ViewResponseTrait.php(54): view() #17 …/app/Module/LifespansChartModule.php(226): Fisharebest\Webtrees\Module\AbstractModule-&gt;viewResponse() #18 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Module\LifespansChartModule-&gt;handle() #19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process() <b>#20 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(277): Middleland\Dispatcher-&gt;handle()</b> #21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule-&gt;process() <b>#22 …/modules_v4/faces/src/Modules/FacesModule.php(94): Middleland\Dispatcher-&gt;handle()</b> #23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule-&gt;process() <b>#24 …/modules_v4/webtrees-reminder/src/Modules/ReminderModule.php(97): Middleland\Dispatcher-&gt;handle()</b> #25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule-&gt;process() <b>#26 …/modules_v4/change_language_with_url/ChangeLanguageWithURL.php(143): Middleland\Dispatcher-&gt;handle()</b> #27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): ChangeLanguageWithURLNamespace\ChangeLanguageWithURL-&gt;process() #28 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher-&gt;handle() #29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule-&gt;process() #30 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher-&gt;handle() #31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion-&gt;process() #32 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher-&gt;handle() #33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() #34 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #35 …/app/Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch() #36 …/app/Http/Middleware/Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch() #37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process() #38 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle() #39 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #40 …/app/Http/Middleware/UseTransaction.php(44): Illuminate\Database\Connection-&gt;transaction() #41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process() #42 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher-&gt;handle() #43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process() #44 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher-&gt;handle() #45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process() #46 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle() #47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process() #48 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher-&gt;handle() #49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process() #50 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher-&gt;handle() #51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process() #52 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle() #53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process() #54 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher-&gt;handle() #55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process() #56 …/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher-&gt;handle() #57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process() #58 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher-&gt;handle() #59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process() #60 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher-&gt;handle() #61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process() #62 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher-&gt;handle() #63 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process() #64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process() #65 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle() #66 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process() #67 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher-&gt;handle() #68 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process() #69 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle() #70 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process() #71 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle() #72 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process() #73 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle() #74 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process() #75 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #76 …/app/Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch() #77 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() #78 …/index.php(51): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() #79 {main}`

**Comment by ric2016** [comment]
your stacktrace, formatted:

```
Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule …/vendor/aura/router/src/Map.php:189 
#0 …/app/Factories/RouteFactory.php(62): Aura\Router\Map-&gt;getRoute() 
#1 …/app/Helpers/functions.php(132): Fisharebest\Webtrees\Factories\RouteFactory-&gt;route() <b>
#2 …/modules_v4/vesta_extended_relationships/ExtendedRelationshipModule.php(660): route()</b> <b>
#3 …/modules_v4/vesta_extended_relationships/ExtendedRelationshipModule.php(689): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule-&gt;chartUrl()</b> 
#4 …/app/Module/ChartsMenuModule.php(99): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule-&gt;chartMenu() 
#5 [internal function]: Fisharebest\Webtrees\Module\ChartsMenuModule::Fisharebest\Webtrees\Module\{closure}() 
#6 …/vendor/illuminate/collections/Collection.php(695): array_map() 
#7 …/app/Module/ChartsMenuModule.php(98): Illuminate\Support\Collection-&gt;map() 
#8 …/app/Module/ModuleThemeTrait.php(495): Fisharebest\Webtrees\Module\ChartsMenuModule-&gt;getMenu() 
#9 [internal function]: Fisharebest\Webtrees\Module\WebtreesTheme::Fisharebest\Webtrees\Module\{closure}() 
#10 …/vendor/illuminate/collections/Collection.php(695): array_map() 
#11 …/app/Module/ModuleThemeTrait.php(495): Illuminate\Support\Collection-&gt;map() 
#12 …/resources/views/layouts/default.phtml(112): Fisharebest\Webtrees\Module\WebtreesTheme-&gt;genealogyMenu() 
#13 …/app/View.php(183): include(&#039;...&#039;) 
#14 …/app/View.php(278): Fisharebest\Webtrees\View-&gt;render() 
#15 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make() 
#16 …/app/Http/ViewResponseTrait.php(54): view() 
#17 …/app/Module/LifespansChartModule.php(226): Fisharebest\Webtrees\Module\AbstractModule-&gt;viewResponse() 
#18 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Module\LifespansChartModule-&gt;handle() 
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler-&gt;process() <b>
#20 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(277): Middleland\Dispatcher-&gt;handle()</b> 
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule-&gt;process() <b>
#22 …/modules_v4/faces/src/Modules/FacesModule.php(94): Middleland\Dispatcher-&gt;handle()</b> 
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule-&gt;process() <b>
#24 …/modules_v4/webtrees-reminder/src/Modules/ReminderModule.php(97): Middleland\Dispatcher-&gt;handle()</b> 
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule-&gt;process() <b>
#26 …/modules_v4/change_language_with_url/ChangeLanguageWithURL.php(143): Middleland\Dispatcher-&gt;handle()</b> 
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): ChangeLanguageWithURLNamespace\ChangeLanguageWithURL-&gt;process() 
#28 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher-&gt;handle() 
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule-&gt;process() 
#30 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher-&gt;handle() 
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion-&gt;process() 
#32 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher-&gt;handle() 
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() 
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() 
#35 …/app/Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch() 
#36 …/app/Http/Middleware/Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch() 
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process() 
#38 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle() 
#39 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() 
#40 …/app/Http/Middleware/UseTransaction.php(44): Illuminate\Database\Connection-&gt;transaction() 
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process() 
#42 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher-&gt;handle() 
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process() 
#44 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher-&gt;handle() 
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process() 
#46 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle() 
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process() 
#48 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher-&gt;handle() 
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process() 
#50 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher-&gt;handle() 
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process() 
#52 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle() 
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process() 
#54 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher-&gt;handle() 
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process() 
#56 …/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher-&gt;handle() 
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process() 
#58 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher-&gt;handle() 
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process() 
#60 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher-&gt;handle() 
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process() 
#62 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher-&gt;handle() 
#63 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process() 
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process() 
#65 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle() 
#66 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process() 
#67 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher-&gt;handle() 
#68 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process() 
#69 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle() 
#70 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process()
#71 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle() 
#72 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process() 
#73 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle() 
#74 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process() 
#75 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() 
#76 …/app/Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch() 
#77 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() 
#78 …/index.php(51): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() 
#79 {main}
```

There is something wrong in the middleware stack.
All middleware after 'UseTransaction' from this isn't called, including 'BootModules', which explains the subsequent error.
[See the list here](https://github.com/fisharebest/webtrees/blob/407d63eb26e871468afafb8aad149ce06ac142a8/app/Webtrees.php#L157). Everything up to 'UseTransaction' appears in the stack, but nothing after.

Normal stack trace looks like this:

```
[...]
#19 C:\xampp814\htdocs\dev\webtrees\app\Http\Middleware\Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#20 C:\xampp814\htdocs\dev\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#21 C:\xampp814\htdocs\dev\webtrees\app\Http\Middleware\BootModules.php(60): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#22 C:\xampp814\htdocs\dev\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#23 C:\xampp814\htdocs\dev\webtrees\app\Http\Middleware\RegisterGedcomTags.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#24 C:\xampp814\htdocs\dev\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#25 C:\xampp814\htdocs\dev\webtrees\app\Http\Middleware\LoadRoutes.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#26 C:\xampp814\htdocs\dev\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#27 C:\xampp814\htdocs\dev\webtrees\app\Http\Middleware\CheckForNewVersion.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#28 C:\xampp814\htdocs\dev\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#29 C:\xampp814\htdocs\dev\webtrees\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#30 C:\xampp814\htdocs\dev\webtrees\vendor\illuminate\database\Concerns\ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#31 C:\xampp814\htdocs\dev\webtrees\app\Http\Middleware\UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3)
#32 C:\xampp814\htdocs\dev\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#33 C:\xampp814\htdocs\dev\webtrees\app\Http\Middleware\DoHousekeeping.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#34 C:\xampp814\htdocs\dev\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
[...]
```

I do not know how this can occur, anyway it's not Vesta-specific and should be investigated further in webtrees.
